#!/usr/bin/python3

from gpiozero import LED
import sys, os, re, time, fcntl

fd = sys.stdin.fileno()
fl = fcntl.fcntl(fd, fcntl.F_GETFL)
fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)

dtr = re.compile('.+TIOCM_DTR.+')
start = time.time()
pin = 4
reset = LED(pin)


def reset():
    reset.on()
    time.sleep(0.12)
    reset.off()


def process():
  while True:
    try:
      duration = time.time() - start
      input = sys.stdin.readline().strip()
      if dtr.match(input):
        reset()
        return
      elif duration > 2.0:
        return
    except:
      continue


print("avrdude-original: Using autoreset DTR on GPIO Pin " + str(pin))
reset()
process()
