#!/bin/bash
# postinst script for fabscanpi-server
#
# see: dh_installdeb(1)

set -e

FABSCAN_USER=fabscan
CONF_DIR=/etc/fabscanpi
LOG_DIR=/var/log/fabscanpi
SCANS_DIR=/var/scans
PID_DIR=/var/run/fabscanpi

chmod 777 /usr/bin/autoreset
chmod 777 /usr/bin/avrdude-autoreset

# Allow $FABSCAN_USER to change the config and setting files
chown -R $FABSCAN_USER:nogroup $CONF_DIR


# Create log directory if necessary
if [ ! -d $LOG_DIR ];then
    mkdir -p $LOG_DIR
fi
# Change permission to allow $FABSCAN_USER to write logs
chown -R $FABSCAN_USER:nogroup $LOG_DIR

# Create data directory if necessary
if [ ! -d $SCANS_DIR ];then
    mkdir -p $SCANS_DIR
fi

#create folder for pid file
if [ ! -d $PID_DIR ];then
    mkdir -p $PID_DIR
    chown -R $FABSCAN_USER:nogroup $PID_DIR
fi

# Change permission to allow $FABSCAN_USER to write data
chown -R $FABSCAN_USER:nogroup $SCANS_DIR

#/etc/init.d/fabscanpi-server start

systemctl enable fabscanpi-server
systemctl start fabscanpi-server

# add fabscan server to default runlevels
#update-rc.d fabscanpi-server defaults

exit 0