#!/bin/bash
# postrm script for script for fabscanpi-server
#
# see: dh_installdeb(1)

set -e

SERVICE=fabscanpi-server
LOG_DIR=/var/log/fabscanpi
PIDFILE=/var/run/$SERVICE.pid

INIT_SCRIPT=/etc/init.d/$SERVICE

if [ -d /usr/local/fabscanpi/www/ ];then
    rm -R /usr/local/fabscanpi/www/
fi

if [ -d $LOG_DIR ];then
    rm -R $LOG_DIR
fi

exit 0