#!/bin/bash
# preinst script for script for fabscanpi-server
#
# see: dh_installdeb(1)

set -e

SERVICE=fabscanpi-server
INIT_SCRIPT=/etc/init.d/$SERVICE

if ps ax | grep -v grep | grep -v $0 | grep $SERVICE > /dev/null
then
        if [ -f $INIT_SCRIPT ];then
            echo "$SERVICE is running shutting down..."
            $INIT_SCRIPT stop
        fi
fi

LOG_DIR=/var/log/fabscanpi
CONF_DIR=/etc/fabscanpi
SCANS_DIR=/usr/local/fabscanpi/scans

if [ ! -d $LOG_DIR ];then
    mkdir $LOG_DIR
    chown -R pi:pi $LOG_DIR
fi

if [ ! -d $CONF_DIR ];then
    mkdir $CONF_DIR
    chown -R pi:pi $CONF_DIR
fi

if [ ! -d $SCANS_DIR ];then
    mkdir -p $SCANS_DIR
    chown -R pi:pi $SCANS_DIR
fi


exit 0