#!/bin/bash
# preinst script for script for fabscanpi-server
#
# see: dh_installdeb(1)

set -e

FABSCAN_USER=fabscan
SERVICE=fabscanpi-server
INIT_SCRIPT=/etc/init.d/$SERVICE
SCANS_DIR=/var/scans

echo "KERNEL=="ttyAMA0", SYMLINK+="ttyS0",GROUP="dialout",MODE:=0666" > /etc/udev/rules.d/80-arduinopi.rules

if [ -f /etc/inittab ]; then
  		sed -i -e 's/T0:23:respawn:/#T0:23:respawn:/g' /etc/inittab
fi

if ps ax | grep -v grep | grep -v $0 | grep $SERVICE > /dev/null
then
        if [ -f $INIT_SCRIPT ];then
            echo "$SERVICE is running shutting down..."
           #$INIT_SCRIPT stop
           systemctl stop fabscanpi-server
        fi
fi

adduser --system $FABSCAN_USER --home $SCANS_DIR --no-create-home > /dev/null 2>&1 || true
usermod -a -G dialout -G pi -G sudo -G tty $FABSCAN_USER

usermod -a -G dialout -G pi -G sudo -G tty pi

exit 0
