#!/usr/bin/env python
__author__ = "Mario Lukas"
__copyright__ = "Copyright 2015"
__license__ = "AGPL"
__maintainer__ = "Mario Lukas"
__email__ = "info@mariolukas.de"

import sys
sys.path.append('/usr/share/pyshared')

import fabscan


def main():

    fabscan.main()

if __name__ == "__main__":
    main()