#!/usr/bin/env python3
__author__ = "Mario Lukas"
__copyright__ = "Copyright 2017"
__license__ = "GPL v2"
__maintainer__ = "Mario Lukas"
__email__ = "info@mariolukas.de"

import fabscan
import os

def main():
    #os.system('/usr/bin/avrdude-autoreset -c arduino -p m328p -P /dev/ttyAMA0 -b 115200  -l /dev/null')
    fabscan.main()

if __name__ == "__main__":
    main()